org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2]
neo_version=26.1.2.75

## Mod Properties

mod_id=machines
mod_name=Synergy Machines
mod_license=Ora Et Labora License
mod_version=1.0
mod_group_id=com.synergy.machines
mod_authors=DevDyna
mod_description=Functional one-block upgradable machine for anything you will want

## lib
cakesticklib_version=[1.17.2,)
cakesticklib=8817136

## Compats

jei_version=29.5.0.26



